---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: CentOS7
  remote_user: root
  roles:
    - common
    - observium
#    - monitoring
#    - docker
