---
# Handlers for common notifications

- name: restart systemD
  service: daemon_reload=yes

- name: Restart httpd
  service:
      name: httpd
      state: restarted

- name: Restart mariadb
  service:
      name: mariadb
      state: restarted

- name: Restart cron
  service:
      name: crond
      state: restarted

- name: Restart firewalld
  service:
      name: firewalld
      state: restarted
