- name: Copy Docker Repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-engine
    - python-pip

- name: Start Docker
  service:
      name: yum-cron
      state: started
      enabled: yes
      daemon_reload: yes
  tags: yum, service

- name: Firewalld Allow Docker API
  firewalld:
    port: 4243/tcp
    permanent: true
    state: enabled
  notify: Restart firewalld
