---
# Handlers for common notifications

- name: Restart firewalld
  service:
      name: firewalld
      state: restarted

- name: Restart snmpd
  systemd:
      name: snmpd
      state: restarted

- name: Restart nrpe
  systemd:
      name: nrpe
      state: restarted
