- name: Copy Docker Repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-engine
    - python-pip

- name: Start Docker
  service:
      name: yum-cron
      state: started
      enabled: yes
      daemon_reload: yes
  tags: yum, service

- name: Install Docker Compose
  pip:
    state: present
    name: docker-compose

- name: Install Docker Compose
  pip:
    state: present
    name: docker-py>=1.7.0
